// old/memorynote/main/apps/web-vue/src/components/SectionCard.vue
<script setup lang="ts">
defineProps<{
  title: string;
  eyebrow?: string;
}>();
</script>

<template>
  <article class="section-card">
    <div class="section-card__head">
      <p v-if="eyebrow" class="section-card__eyebrow">{{ eyebrow }}</p>
      <h3 class="section-card__title">{{ title }}</h3>
    </div>
    <div class="section-card__body">
      <slot />
    </div>
  </article>
</template>

// apps/web/src/components/SectionCard.tsx
export function SectionCard({
  title,
  eyebrow,
  children,
}: {
  title: string;
  eyebrow?: string;
  children: React.ReactNode;
}) {
  return (
    <article className="section-card">
      <div className="section-card__head">
        {eyebrow && <p className="section-card__eyebrow">{eyebrow}</p>}
        <h3 className="section-card__title">{title}</h3>
      </div>
      <div className="section-card__body">{children}</div>
    </article>
  );
}
