// old/memorynote/v2-nextjs/apps/web/src/components/AppShell.tsx
"use client";

import Link from "next/link";
import type { Route } from "next";
import { usePathname } from "next/navigation";

const sections = [
  { label: "首页", to: "/", description: "仪表盘、统计概览" },
  { label: "对话", to: "/chat/new", description: "AI 对话" },
  { label: "知识工作台", to: "/memory/graph", description: "知识图谱可视化" },
  { label: "学习收件箱", to: "/memory/inbox", description: "待确认候选记忆" },
  { label: "文档记忆", to: "/memory/documents", description: "已存储的记忆文档" },
  { label: "维基", to: "/wiki", description: "结构化知识库" },
  { label: "标签", to: "/memory/labels", description: "记忆标签与分类管理" },
  { label: "模型设置", to: "/settings/models", description: "模型路由、API Key" },
];

function isNavActive(path: string, itemTo: string) {
  if (itemTo === "/") return path === "/";
  if (itemTo === "/chat/new") return path.startsWith("/chat");
  if (itemTo === "/memory/inbox") return path === "/memory/inbox";
  if (itemTo === "/wiki") return path === "/wiki" || path.startsWith("/wiki/");
  if (itemTo === "/settings/models") return path.startsWith("/settings");
  return path.startsWith(itemTo);
}

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  return (
    <div className="shell">
      <aside className="shell__sidebar">
        <div className="brand">
          <div className="brand__badge">MN</div>
          <div>
            <p className="brand__eyebrow">知识沉淀系统</p>
            <h1 className="brand__title">MemoryNote</h1>
          </div>
        </div>

        <nav className="nav">
          {sections.map((item) => (
            <Link
              key={item.to}
              href={item.to as Route}
              className={`nav__item${isNavActive(pathname, item.to) ? " nav__item--active" : ""}`}
              title={item.description}
            >
              <span className="nav__label">{item.label}</span>
              <span className="nav__description">{item.description}</span>
            </Link>
          ))}
        </nav>

        <div className="sidebar-card">
          <p className="sidebar-card__label">版本</p>
          <p className="sidebar-card__value">v2 · Next.js 15</p>
          <p className="sidebar-card__hint">单一前端 · React 19 · @core/core</p>
        </div>
      </aside>

      <main className="shell__content">
        <section className="shell__panel">{children}</section>
      </main>
    </div>
  );
}

// apps/web-vue/src/components/AppShell.vue
<script setup lang="ts">
import { computed, watch } from "vue";
import { RouterLink, RouterView, useRoute } from "vue-router";

import { useSessionStore } from "@/stores/session";

const route = useRoute();
const session = useSessionStore();

const sections = [
  { label: "对话", to: "/home/conversation", description: "主工作区：AI 对话与会话历史" },
  { label: "知识工作台", to: "/home/memory/graph", description: "知识图谱可视化、力导向布局、社区检测" },
  { label: "学习收件箱", to: "/home/memory/graph/inbox", description: "待确认候选记忆、批量处理" },
  { label: "文档记忆", to: "/home/memory/documents", description: "已存储的记忆文档、导入文件" },
  { label: "维基", to: "/home/wiki", description: "结构化知识库、版本历史" },
  { label: "标签", to: "/home/memory/labels", description: "记忆标签与分类管理" },
  { label: "模型设置", to: "/settings/workspace/models", description: "工作区模型路由、API Key" },
];

const title = computed(() => {
  if (route.path.startsWith("/home/memory/graph/inbox")) return "学习收件箱";
  if (route.path.startsWith("/home/memory/graph")) return "知识工作台";
  if (route.path.startsWith("/home/memory/documents")) return "文档记忆";
  if (route.path.startsWith("/home/wiki")) return "维基";
  if (route.path.startsWith("/home/memory/labels")) return "记忆标签";
  if (route.path.startsWith("/settings")) return "模型设置";
  return "对话";
});

const isGraphRoute = computed(() => route.path.startsWith("/home/memory/graph"));

function isNavActive(itemTo: string) {
  if (itemTo === "/home/memory/graph/inbox") {
    return route.path === "/home/memory/graph/inbox";
  }
  if (itemTo === "/home/memory/graph") {
    return (
      route.path === "/home/memory/graph" ||
      route.path.startsWith("/home/memory/graph/object")
    );
  }
  return route.path.startsWith(itemTo);
}

watch(
  title,
  (value) => {
    document.title = `MemoryNote · ${value}`;
  },
  { immediate: true },
);
</script>

<template>
  <div class="shell" :class="{ 'shell--graph': isGraphRoute }">
    <aside class="shell__sidebar">
      <div class="brand">
        <div class="brand__badge">MN</div>
        <div>
          <p class="brand__eyebrow">知识沉淀系统</p>
          <h1 class="brand__title">MemoryNote</h1>
        </div>
      </div>

      <nav class="nav">
        <RouterLink
          v-for="item in sections"
          :key="item.to"
          :to="item.to"
          class="nav__item"
          :class="{ 'nav__item--active': isNavActive(item.to) }"
        >
          <span class="nav__label">{{ item.label }}</span>
          <span class="nav__description">{{ item.description }}</span>
        </RouterLink>
      </nav>

      <div class="sidebar-card">
        <p class="sidebar-card__label">当前工作区</p>
        <p class="sidebar-card__value">{{ session.user?.workspaceId ?? "加载中..." }}</p>
        <p class="sidebar-card__hint">知识工作台是对话后的整理层，不替代主对话界面。</p>
      </div>
    </aside>

    <main class="shell__content" :class="{ 'shell__content--graph': isGraphRoute }">
      <header class="shell__header">
        <div>
          <p class="shell__eyebrow">个人知识沉淀系统</p>
          <h2 class="shell__headline">{{ title }}</h2>
        </div>
        <div class="shell__meta">
          <span class="chip">{{ session.user?.name ?? "用户" }}</span>
          <span class="chip chip--accent">{{ session.user?.email ?? "加载中..." }}</span>
        </div>
      </header>

      <section class="shell__panel" :class="{ 'shell__panel--graph': isGraphRoute }">
        <RouterView />
      </section>
    </main>
  </div>
</template>
